# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.16.0]  # 把 node.js 版本記錄在這，之後可以重新取出作為 cache key

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # install node.js use v16  test1
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}


      - name: Cache Node Modules
        uses: actions/cache@v3
        with:
          path: node_modules
          # cache key 包含了所有我們希望固定的資訊：OS，node 版本，以及 package-lock.json 的檔案內容，使用 hashFiles 將檔案內容轉換成字串
          key: node-modules-${{ runner.os }}-${{ matrix.node-version }}-${{ hashFiles('package-lock.json') }}

      # Runs a single command using the runners shell
      # - name: install dependencies
      #   run: npm install

      # https://docs.npmjs.com/cli/v8/commands/npm-ci
      - name: Install Packages
        run: test -d node_modules && echo "node_modules exists" || npm ci

      # Runs a single command using the runners shell
      - name: try to build the project
        run: npm run build

      # use actions-gh-pages to deploy dist to gh-pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          # github will auto-generate a token for this job and use it 
          github_token: ${{ secrets.DeployToken }}
          publish_dir: ./dist
